/**
 * File generated from the model::OutOfAnyPackages uml Class
 * Generated by the Acceleo 3 <i>UML to Java</i> generator.
 */


// Start of user code imports	

// End of user code

/**
 * Description of OutOfAnyPackages.
 */
public class OutOfAnyPackages {
    // Start of user code (user defined attributes)
    
    // End of user code
    
    /**
     * The constructor.
     */
    public OutOfAnyPackages() {
    	// Start of user code constructor
    	super();
    	// End of user code
    }
    
    // Start of user code (user defined methods)
    
    // End of user code
    
    
}
